[package]
name = "prawn"
version = "0.1.0"
authors = []
edition = "2018"
license = "MIT"

[dependencies]
amethyst = "0.14.0"
rand = "0.7"

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
